# GitHub Actions workflow for CI/CD
# TODO: Complete this pipeline.

name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: shahil-project-app  # TODO: Update with your ECR repo name
  EKS_CLUSTER_NAME: one-eks  # TODO: Update if using EKS
  # ECS_CLUSTER_NAME: document-service-cluster  # TODO: Update if using ECS

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Detect changes in app folder
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'app/**'     
              
      - name: Set up Python
        if: steps.changes.outputs.app == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
                        
      - name: Install dependencies
        if: steps.changes.outputs.app == 'true'
        run: |
          python -m pip install --upgrade pip
          cd app
          pip install -r requirements.txt
      
      - name: Run tests
        #if: ${{ hashFiles('app/**') != '' }}
        #if: ${{ always() && hashFiles('app/**') != '' }}
        if: steps.changes.outputs.app == 'true'
        run: |
          cd app
          python -m pytest -q --maxfail=2 --disable-warnings
      
      - name: Build Docker image
        if: steps.changes.outputs.app == 'true'
        run: |
          cd app
          docker build -t $ECR_REPOSITORY:latest .
      
      - name: Run Trivy vulnerability scanner
        if: steps.changes.outputs.app == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:latest
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security
        if: steps.changes.outputs.app == 'true'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [build-and-test]
    #if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        
        
      - name: Detect changes in infrastructure folder
        id: changesininfra
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infrastructure:
              - 'infrastructure/**'

      - name: Configure AWS credentials
        if: steps.changesininfra.outputs.infrastructure == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        if: steps.changesininfra.outputs.infrastructure == 'true'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Terraform Init
        if: steps.changesininfra.outputs.infrastructure == 'true'
        run: |
          cd infrastructure
          terraform init
      
      - name: Terraform Plan
        if: steps.changesininfra.outputs.infrastructure == 'true'
        run: |
          cd infrastructure
          terraform plan -no-color
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Detect changes in infrastructure folder
        id: changesininfra
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infrastructure:
              - 'infrastructure/**'
              
      - name: Terraform Init
        if: steps.changesininfra.outputs.infrastructure == 'true'
        run: |
          cd infrastructure
          terraform init
      
      - name: Terraform Apply
        if: steps.changesininfra.outputs.infrastructure == 'true'
        #terraform state show aws_cloudwatch_log_group.eks_control_plane >/dev/null 2>&1 || \
        #terraform import aws_cloudwatch_log_group.eks_control_plane "/aws/eks/one-eks/cluster"
        run: |
          cd infrastructure
          terraform apply -auto-approve
          
      - name: Detect changes in app folder
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'app/**'
              
      - name: Login to Amazon ECR
        if: steps.changes.outputs.app == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag, and push image to Amazon ECR
        if: steps.changes.outputs.app == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          
      # TODO: Add deployment steps based on your choice (EKS or ECS)
      # Option A: EKS Deployment.
      - name: Configure kubectl
        if: steps.changes.outputs.app == 'true'
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          kubectl delete pod -l app=document-service

      # - name: Deploy to EKS (Kubernetes Manifests)
      #   run: |
      #     # Update image in deployment.yaml
      #     sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" kubernetes/deployment.yaml
      #     sed -i "s|REPLACE_WITH_ECR_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" kubernetes/deployment.yaml
      #     sed -i "s|^ *image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" kubernetes/deployment.yaml
      #     sed -i "s|^\([[:space:]]*\)image:.*|\1image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}|" kubernetes/deployment.yaml
      #     kubectl apply -f kubernetes/
      #     kubectl apply -f kubernetes/
          
      - name: Deploy to EKS (Kubernetes Manifests)
        if: steps.changes.outputs.app == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f kubernetes/
          kubectl -n default set image deployment/document-service \
          document-service=$ECR_REGISTRY/$ECR_REPOSITORY:latest
          kubectl -n default rollout status deployment/document-service --timeout=180s
          
      - name: Verify deployment
        if: steps.changes.outputs.app == 'true'
        run: |
          kubectl get deploy document-service -o jsonpath='{.spec.template.spec.containers[0].image}'; echo
          kubectl get secret document-service-secrets -n default
          kubectl get sa document-service-sa -n default
          kubectl get pods -l app=document-service
          kubectl logs -l app=document-service --tail=50

      - name: Smoke test API
        if: steps.changes.outputs.app == 'true'
        run: |
          kubectl run curl-test --rm -i --restart=Never \
          --image=curlimages/curl:8.5.0 -- \
          curl -s http://document-service/health
          
      - name: Run integration tests
        run: |
          # Test the deployed service
          ALB_DNS=$(terraform -chdir=infrastructure output -raw document_clb_dns)
          curl -f https://$ALB_DNS/health
